# Data Preparation. Практическая работа

## Цели практической работы
1. Потренироваться определять типы переменных в датасете, целевую переменную из постановки задачи, распределение переменных.
2. Познакомиться с задачей, предстоящей на этапе моделирования.
3. Начать исследовать данные для этапа моделирования.

## Что входит в практическую работу
1. Загрузить датасет и ознакомиться с ним.
2. Исследовать переменные датасета.
3. Определить типы переменных в датасете.
4. Определить целевую переменную в данных и распределение переменных.

## Что оценивается
- Программа выдаёт верный ответ на заданном наборе данных.
- Описаны причины выбранного решения, если требуется.
- Код читабелен: переменным даны осмысленные названия, отступы и правила расстановки пробелов соблюдены.
- Репозиторий проекта содержит осмысленные коммиты, содержащие конкретные реализованные фичи, ветки названы согласно назначению, лишние файлы не хранятся в репозитории.
- В репозитории проекта соблюдена иерархия директорий согласно списку модулей и содержащихся в них уроках.
- Репозиторий проекта содержит файлы с данными, полученными в результате выполнения практической работы.

## Как отправить работу на проверку
Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему проверяющему преподавателю.

## Задача

Начиная с этого урока вы начнёте исследовать и готовить данные для этапа моделирования.

Вам предстоит работать с небольшой выборкой из коллекции подержанных автомобилей, выставленных на продажу в Соединённых Штатах, представленной в файле `data/vehicles_dataset.csv`. На этих данных вы построите первую модель классификации, определяющую категорию цены подержанного автомобиля в зависимости от характеристик транспортного средства.
В этой практической работе вы загрузите датасет и начнёте его исследование.


## Описание датасета:
- `id`: идентификатор записи;
- `url`: URL записи о продаже;
- `region`: регион;
- `region_url`: URL региона;
- `price`: стоимость;
- `year`: год выпуска;
- `manufacturer`: производитель;
- `model`: модель;
- `condition`: состояние;
- `cylinders`: количество цилиндров;
- `fuel`: тип топлива;
- `odometer`: количество пройденных миль;
- `title_status`: статус;
- `transmission`: коробка передач;
- `VIN`: идентификационный номер;
- `drive`: тип привода;
- `size`: размер;
- `type`: кузов;
- `paint_color`: цвет;
- `image_url`: URL изображения;
- `description`: указанное описание;
- `county`: страна;
- `state`: штат;
- `lat`: широта;
- `long`: долгота;
- `posting_date`: дата размещения объявления о продаже;
- `price_category`: категория цены.

In [ ]:
# Импортируйте необходимые библиотеки

### Задача 1. Загрузка датасета и ознакомление с ним
**Что нужно сделать**

Для начала требуется загрузить датасет и ознакомиться с его характеристиками.

1. Загрузите датасет из `data/vehicles_dataset.csv` и выведите его.

In [3]:
# Ваш код здесь
import pandas as pd

2. Выведите размер датасета.

In [4]:
# Ваш код здесь
df = pd.read_csv('vehicles_dataset.csv')

# Display the first few rows of the dataframe
print(df.head())

           id                                                url  \
0  7308295377  https://chattanooga.craigslist.org/ctd/d/chatt...
1  7316380095  https://newjersey.craigslist.org/ctd/d/carlsta...
2  7313733749  https://reno.craigslist.org/ctd/d/atlanta-2017...
3  7308210929  https://fayetteville.craigslist.org/ctd/d/rale...
4  7316474668  https://newyork.craigslist.org/lgi/cto/d/baldw...

          region                           region_url  price    year  \
0    chattanooga   https://chattanooga.craigslist.org  54990  2020.0
1   north jersey     https://newjersey.craigslist.org  16942  2016.0
2   reno / tahoe          https://reno.craigslist.org  35590  2017.0
3   fayetteville  https://fayetteville.craigslist.org  14500  2013.0
4  new york city       https://newyork.craigslist.org  21800  2021.0

  manufacturer                   model condition    cylinders  ...    type  \
0          ram  2500 crew cab big horn      good          NaN  ...  pickup
1         ford    explorer 4wd 4dr xlt       NaN  6 cylinders  ...     SUV
2   volkswagen        golf r hatchback      good          NaN  ...   sedan
3       toyota                    rav4       NaN          NaN  ...   wagon
4       nissan                  altima       new  4 cylinders  ...     NaN

   paint_color                                          image_url  \
0       silver  https://images.craigslist.org/00N0N_1xMPvfxRAI...
1        black  https://images.craigslist.org/00x0x_26jl9F0cnL...
2          NaN  https://images.craigslist.org/00y0y_eeZjWeiSfb...
3        white  https://images.craigslist.org/00606_iGe5iXidib...
4          NaN  https://images.craigslist.org/00V0V_3pSOiPZ3Sd...

                                         description county state        lat  \
0  Carvana is the safer way to buy a car During t...    NaN    tn  35.060000
1  ***Call Us for more information at: 201-635-14...    NaN    nj  40.821805
2  Carvana is the safer way to buy a car During t...    NaN    ca  33.779214
3  2013 Toyota RAV4 XLE 4dr SUV     Offered by: R...    NaN    nc  35.715954
4  2021 Nissan Altima Sv with Only 8 K Miles Titl...    NaN    ny  40.654800

        long              posting_date price_category
0 -85.250000  2021-04-17T12:30:50-0400           high
1 -74.061962  2021-05-03T15:40:21-0400         medium
2 -84.411811  2021-04-28T03:52:20-0700           high
3 -78.655304  2021-04-17T10:08:57-0400         medium
4 -73.609700  2021-05-03T18:32:06-0400         medium

[5 rows x 27 columns]

3. Выведите список колонок датасета.

In [5]:
# Ваш код здесь
# Print the list of columns in the dataset
print("Columns list:", df.columns.tolist())

Columns list: ['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer', 'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status', 'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color', 'image_url', 'description', 'county', 'state', 'lat', 'long', 'posting_date', 'price_category']

4. Выведите описательные статистики для всего датасета (обязательно укажите верный параметр для этого).

In [6]:
# Ваш код здесь
# Print descriptive statistics for the dataset
print(df.describe(include='all'))

                  id                                                url  \
count   1.005000e+04                                              10050
unique           NaN                                              10000
top              NaN  https://roswell.craigslist.org/cto/d/artesia-1...
freq             NaN                                                  2
mean    7.311544e+09                                                NaN
std     4.475414e+06                                                NaN
min     7.208550e+09                                                NaN
25%     7.308193e+09                                                NaN
50%     7.312756e+09                                                NaN
75%     7.315275e+09                                                NaN
max     7.317090e+09                                                NaN

                 region                         region_url         price  \
count             10050                              10050  1.005000e+04
unique              393                                405           NaN
top     kansas city, MO  https://kansascity.craigslist.org           NaN
freq                 86                                 86           NaN
mean                NaN                                NaN  2.068429e+04
std                 NaN                                NaN  1.243216e+05
min                 NaN                                NaN  5.000000e+02
25%                 NaN                                NaN  7.900000e+03
50%                 NaN                                NaN  1.574950e+04
75%                 NaN                                NaN  2.799000e+04
max                 NaN                                NaN  1.234568e+07

                year manufacturer  model condition    cylinders  ...   type  \
count   10014.000000         9665   9921      6268         5953  ...   7845
unique           NaN           39   3466         6            8  ...     13
top              NaN         ford  f-150      good  6 cylinders  ...  sedan
freq             NaN         1647    151      3134         2288  ...   1981
mean     2010.917815          NaN    NaN       NaN          NaN  ...    NaN
std         9.697849          NaN    NaN       NaN          NaN  ...    NaN
min      1915.000000          NaN    NaN       NaN          NaN  ...    NaN
25%      2008.000000          NaN    NaN       NaN          NaN  ...    NaN
50%      2013.000000          NaN    NaN       NaN          NaN  ...    NaN
75%      2017.000000          NaN    NaN       NaN          NaN  ...    NaN
max      2022.000000          NaN    NaN       NaN          NaN  ...    NaN

        paint_color                                          image_url  \
count          7087                                              10048
unique           12                                               9081
top           white  https://images.craigslist.org/00N0N_1xMPvfxRAI...
freq           1916                                                191
mean            NaN                                                NaN
std             NaN                                                NaN
min             NaN                                                NaN
25%             NaN                                                NaN
50%             NaN                                                NaN
75%             NaN                                                NaN
max             NaN                                                NaN

                                              description county  state  \
count                                               10048    0.0  10050
unique                                               9845    NaN     51
top     PLEASE VIEW THE FREE CARFAX HISTORY REPORT AT ...    NaN     ca
freq                                                    7    NaN   1113
mean                                                  NaN    NaN    NaN
std                                                   NaN    NaN    NaN
min                                                   NaN    NaN    NaN
25%                                                   NaN    NaN    NaN
50%                                                   NaN    NaN    NaN
75%                                                   NaN    NaN    NaN
max                                                   NaN    NaN    NaN

                lat         long              posting_date price_category
count   9951.000000  9951.000000                     10048          10050
unique          NaN          NaN                      9957              3
top             NaN          NaN  2021-04-13T09:11:02-0500           high
freq            NaN          NaN                         3           3514
mean      38.590164   -94.161564                       NaN            NaN
std        5.844756    18.123096                       NaN            NaN
min      -67.144243  -158.069300                       NaN            NaN
25%       34.830000  -110.447150                       NaN            NaN
50%       39.285100   -87.999100                       NaN            NaN
75%       42.427590   -80.830000                       NaN            NaN
max       64.947500   173.885502                       NaN            NaN

[11 rows x 27 columns]

### Задача 2. Исследование переменных датасета
**Что нужно сделать**

После ознакомления с датасетом посмотрите, какие значения принимают переменные с характеристиками.

Распечатайте в цикле по каждой колонке название колонки, количество уникальных значений, а затем список возможных значений вместе с их количеством появления в датасете.

При выводе информации по каждой характеристике придерживайтесь шаблона.

```
Характеристика: id
Количество уникальных значений: 10000
Список значений:
7303629857    2
7315995136    2
7316719393    2
7309842734    2
7307971804    2
             ..
7303843163    1
7315223900    1
7309940769    1
7309251820    1
7316428067    1
Name: id, Length: 10000, dtype: int64
```

In [7]:
# Ваш код здесь
for column in df.columns:
    print(f"Characteristic: {column}")
    print("Number of unique values:", df[column].nunique())
    print("List of values:")
    print(df[column].value_counts().head())  # Adjust the number to display as needed
    print("\n")

Characteristic: id
Number of unique values: 10000
List of values:
id
7316028281    2
7310693445    2
7310816094    2
7307639785    2
7312525382    2
Name: count, dtype: int64


Characteristic: url
Number of unique values: 10000
List of values:
url
https://roswell.craigslist.org/cto/d/artesia-1999-ford-f250-super-duty-super/7316028281.html      2
https://pueblo.craigslist.org/ctd/d/tempe-2017-ford-450-f450-450-drw-lariat/7310693445.html       2
https://monroe.craigslist.org/ctd/d/monroe-2019-infiniti-qx60-luxe/7310816094.html                2
https://flint.craigslist.org/ctd/d/davison-2010-ford-150-xlt-supercrew/7307639785.html            2
https://charlotte.craigslist.org/cto/d/myrtle-beach-1947-mercury-hotrod-street/7312525382.html    2
Name: count, dtype: int64


Characteristic: region
Number of unique values: 393
List of values:
region
kansas city, MO          86
minneapolis / st paul    83
grand rapids             82
sarasota-bradenton       82
colorado springs         81
Name: count, dtype: int64


Characteristic: region_url
Number of unique values: 405
List of values:
region_url
https://kansascity.craigslist.org     86
https://minneapolis.craigslist.org    83
https://grandrapids.craigslist.org    82
https://sarasota.craigslist.org       82
https://cosprings.craigslist.org      81
Name: count, dtype: int64


Characteristic: price
Number of unique values: 2227
List of values:
price
6995     112
29990     91
7995      81
8995      76
9995      73
Name: count, dtype: int64


Characteristic: year
Number of unique values: 89
List of values:
year
2017.0    814
2018.0    814
2016.0    748
2013.0    704
2015.0    670
Name: count, dtype: int64


Characteristic: manufacturer
Number of unique values: 39
List of values:
manufacturer
ford         1647
chevrolet    1298
toyota        784
jeep          491
honda         467
Name: count, dtype: int64


Characteristic: model
Number of unique values: 3466
List of values:
model
f-150             151
silverado 1500    110
1500              101
camry              77
silverado          74
Name: count, dtype: int64


Characteristic: condition
Number of unique values: 6
List of values:
condition
good         3134
excellent    2429
like new      482
fair          179
new            31
Name: count, dtype: int64


Characteristic: cylinders
Number of unique values: 8
List of values:
cylinders
6 cylinders     2288
4 cylinders     1825
8 cylinders     1726
5 cylinders       46
10 cylinders      29
Name: count, dtype: int64


Characteristic: fuel
Number of unique values: 5
List of values:
fuel
gas         8447
other        733
diesel       655
hybrid       108
electric      44
Name: count, dtype: int64


Characteristic: odometer
Number of unique values: 7006
List of values:
odometer
100000.0    51
1.0         42
200000.0    37
180000.0    37
140000.0    37
Name: count, dtype: int64


Characteristic: title_status
Number of unique values: 6
List of values:
title_status
clean      9568
rebuilt     171
salvage      92
lien         35
missing      16
Name: count, dtype: int64


Characteristic: transmission
Number of unique values: 3
List of values:
transmission
automatic    7737
other        1633
manual        635
Name: count, dtype: int64


Characteristic: VIN
Number of unique values: 5429
List of values:
VIN
1FMJU1JT1HEA52352    10
JN1AZ4EH8KM420880     8
1FTMF1CP3GKD62143     7
5TFEM5F15KX140773     7
1FTER1EH1LLA36301     7
Name: count, dtype: int64


Characteristic: drive
Number of unique values: 3
List of values:
drive
4wd    3054
fwd    2563
rwd    1409
Name: count, dtype: int64


Characteristic: size
Number of unique values: 4
List of values:
size
full-size      1476
mid-size        824
compact         458
sub-compact      67
Name: count, dtype: int64


Characteristic: type
Number of unique values: 13
List of values:
type
sedan     1981
SUV       1805
pickup    1071
truck      770
other      519
Name: count, dtype: int64


Characteristic: paint_color
Number of unique values: 12
List of values:
paint_color
white     1916
black     1473
silver    1041
red        741
blue       730
Name: count, dtype: int64


Characteristic: image_url
Number of unique values: 9081
List of values:
image_url
https://images.craigslist.org/00N0N_1xMPvfxRAIdz_0gw0co_600x450.jpg    191
https://images.craigslist.org/00R0R_lwWjXSEWNa7z_0x20oM_600x450.jpg     47
https://images.craigslist.org/00v0v_ihZKB5WEx8Rz_0gw0co_600x450.jpg      8
https://images.craigslist.org/00D0D_aqVh7XGmJcQz_0gw0co_600x450.jpg      8
https://images.craigslist.org/01111_l590CdXzJSoz_001001_600x450.jpg      7
Name: count, dtype: int64


Characteristic: description
Number of unique values: 9845
List of values:
description
PLEASE VIEW THE FREE CARFAX HISTORY REPORT AT OUR WEBSITE CARTERSCARSVT.COM OR CALL 802-891-6345 CHECK OUT OUR INVENTORY ON FACEBOOK!!!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 7
CREDIT CARS- $700.00 DOWN- RIGHT ON THE CORNER, RIGHT ON THE CREDIT!!  CALL US TODAY @ 352-204-2923 OR 352-204-2137. $700 DOWN!!!!!  CREDIT CHALLENGES??- NO PROBLEM- COME SEE US TODAY!  WE USE YOUR JOB AS YOUR CREDIT! ALL YOU NEED IS INCOME, PROOF OF INSURANCE, DRIVERS LICENSE, AND $700.00!!!  COME SEE US TODAY AT 320 NE 23RD AVENUE GAINESVILLE, FL 32609  WE ARE OPEN MONDAY- FRIDAY 9:00AM TO 7:00PM AND SATURDAY 9:00AM- 5:00PM  352-204-2137 OR 352-204-2137 CALL US TODAY TO SCHEDULE APPT!!  ⭐ Great Financing Options Available ⭐  ✅ Bad Credit? ✅ No Credit? ✅ First Time Buyer? ✅ We Work With Dozens Of Dealers To Get You Approved Fast Regardless Of Your Credit Situation.  🚘 Ready To Get Behind The Wheel Of Your New Car 🚘  100% APPROVAL! We use your job as your credit!  We Guarantee It! No matter your financial situation, you will drive off the lot in a new car, today.  ✅ Bad Credit ✅ No Credit ✅ Repossession ✅ Foreclosure ✅ SSI ✅ Disability ✅ Government Assistance  YOU'RE APPROVED!  🚘 🚘  ✅ Huge Selection Of Quality Pre-Owned Cars ✅ Leave With Confidence ✅ Trade-In Your Car Today For A Great Discount   📍 Stop By Today                                                                                                                                                                                                                                                                                                                                               5
Call or text today to find out more. (602) 620-6525 Calls only landline (406) 245-1785  Available at Standard Auto Sales 1503 Broadwater Ave. Billings, MT 59102 standardautosales.net   Need help with financing? We have options for most credit situations. We never charge a doc fee! Extended service contracts available. We buy cars and take consignments! Call or text Mike today to find out more. (602) 620-6525  Welcome to Standard Auto Sales, located in Billings, MT, where quality service and customer satisfaction come first. We are here to help you find a vehicle that fits your lifestyle from our wide selection of used cars, trucks, and SUVs. We pride ourselves on a hassle-free car buying experience where your needs come first. Swing by to let us exceed your expectations while finding the perfect vehicle! Do you need financing for your next used vehicle purchase? Do you have a good credit, bad credit or no credit history situation? We work with a variety of financial institutions and we will work hard to get you approved quickly and easily, at the best rate possible! Apply now or call us at (406) 245-1785 or text (602) 620-6525 to schedule a test drive today!                                                                                                                                                                                                                                                                                                5
This truck has sold, but we buy trucks like this. If you know of one of these trucks for sale, we pay a finders fee.  Call Bobby! (636) 587 - 0660    7.3 7.3l 6.6 6.6l 5.9 5.9 6.7 6.7l powerstroke power stroke duramax cummins diesel lly lbz dmax pstroke big block small block big block smallblock sbf sbc bbf bbc efi 302 460 351 6.0 6.0L 5.0L 5.0 5.8L 5.8 7.5L 7.5 496 454 stroker 8.1 8.1L 12v 24v 4x4 four wheel drive 4wd laramie SLT Lariat lt lt1 lt2 lt3 ls club quad single crew cab clubcab quadcab singlecab crewcab cclb long bed longbed short shortbed  ccsb sclb scsb rustfree rust free clean 4door 2-door 2door 4-door ford dodge chevrolet chevy gmc sierra silverado f-250 f-350 f250 f350 ram 2500 3500 1st gen first gen firstgen 2nd gen 2ndgen second gen secondgen 3rd gen 3rdgen third gen thirdgen OBS superduty excursion supercrew supercab super duty 5-speed 6-speed stick shift stickshift manual transmission clutch intercooled inter cooled turbocharged turbo charged lonestar bighorn lone star big horn longhorn long horn low mile lowmile puller camper camp haul hauling hauler tow towing rig gooseneck goose neck 5th wheel fifth wheel 5thwheel fifthwheel hitch                                                                                                                                                                                                                                                                                                     4
35 VEHICLES PRICED UNDER $3000!!!  BIG TIME! TAX TIME! SALE TIME!  CALL US NOW!!! 321-242-0328  30TH YEAR IN BUSINESS!!!!  OUR ADDRESS:  1900 AURORA RD. MELBOURNE, FL 32935  321-242-0328  Call us or visit us now we have a huge selection of honda accord and civic and pilot in stock at all times! we specialize in Toyota Camry and Corolla and Sienna and 3RD Row Suv. We also stock Domestics like Ford Fusion Explorer and Escape and the really nice Edge. if you care looking for Chevy Traverse or Chevrolet Malibu or Impala and Cruze for gas saving we have those as well, including Buick Enclave we always have em! Lacrosse and Regal are here too! Encore is available just call first. We stock Luxury Brands like Acura Lexus and German brands BMW Mercedes Benz and Audi. Dont get us started on Jeep! We love to sell Grand Cherokee and Patriot and Compass! Want a Really Nice Minivan!?! We got Chrysler Town and Country Dodge Grand Caravan and Honda Odyssey Always Here!! Sporty? Charger Challanger Mustang and Camro can be located for you! Are you Hip? Kia Soul and Optima are your bag, we got em!!!! Mazda is here too!! 3 and 6 and CX9. Our Number one seller for 3RD Row is the Dodge Journey and Durango, we always have a bunch in stock, back up camera and push button start bluetooth panoramic sunroof. Cadillac SRX for the luxury driver is here too! Ever driven a Nissan Altima or Sentra or Pathfinder or Rogue, come drive one today and feel the sporty drive!    4
Name: count, dtype: int64


Characteristic: county
Number of unique values: 0
List of values:
Series([], Name: count, dtype: int64)


Characteristic: state
Number of unique values: 51
List of values:
state
ca    1113
fl     690
tx     535
mi     462
ny     453
Name: count, dtype: int64


Characteristic: lat
Number of unique values: 5049
List of values:
lat
43.182400    88
33.779214    79
40.468785    73
33.786500    54
46.234838    50
Name: count, dtype: int64


Characteristic: long
Number of unique values: 5082
List of values:
long
-84.112200     88
-84.411811     79
-74.281707     73
-84.445400     54
-119.128015    50
Name: count, dtype: int64


Characteristic: posting_date
Number of unique values: 9957
List of values:
posting_date
2021-04-13T09:11:02-0500    3
2021-04-26T13:21:00-0700    2
2021-05-03T16:42:17-0400    2
2021-05-04T10:45:14-0700    2
2021-04-13T10:51:11-0400    2
Name: count, dtype: int64


Characteristic: price_category
Number of unique values: 3
List of values:
price_category
high      3514
medium    3294
low       3242
Name: count, dtype: int64

### Задача 3. Определение типов переменных в датасете
**Что нужно сделать**

После ознакомления с характеристиками заполните в таблице, к какому типу относятся некоторые переменные. Для этого на пересечении названия переменной и типа переменной проставьте «X».


|  Переменная    | Дискретная | Непрерывная | Качественная |
|----------------|------------|-------------|--------------|
| id             | X          |             |              |
| region         |            |             |         X     |
| year           |    X        |             |              |
| manufacturer   |            |             |         X     |
| condition      |            |             |         X     |
| fuel           |            |             |       X       |
| odometer       |            |       X      |              |
| title_status   |            |             |        X      |
| transmission   |            |             |        X      |
| VIN            |            |             |         X     |
| drive          |            |             |        X      |
| paint_color    |            |             |       X       |
| state          |            |             |        X      |
| price_category |            |             |       X       |

### Задача 4. Определение целевой переменной в данных и распределения переменных
**Что нужно сделать**

1. Исходя из поставленной задачи определите, в какой колонке находится целевая переменная.

**Ответ:** _ваш ответ_
Исходя из постановки задачи и описания датасета, целевая переменная в данных находится в колонке price_category. Эта переменная классифицирует автомобили по категориям цен и является ключевым элементом для задачи классификации, которую предстоит решить.

Целевая переменная price_category позволяет определить, к какой категории цены относится подержанный автомобиль, на основе его характеристик и данных о продаже. Это может быть высокая, средняя или низкая категория цены.

2. Выведите для каждого значения целевой переменной его долю вхождения в выборку.

In [8]:
# Ваш код здесь
# Calculate and print the distribution of the target variable 'price_category'
print(df['price_category'].value_counts(normalize=True) * 100)

price_category
high      34.965174
medium    32.776119
low       32.258706
Name: proportion, dtype: float64

3. Ещё раз посмотрите на долю или количество вхождений каждого значения целевой переменной в выборку и напишите, какое это распределение. Определить, как распределены значения целевой переменной, в данном случае можно и без графика. 

**Ответ:** _ваш ответ_
Распределение значений целевой переменной price_category является равномерным с небольшим преобладанием высокой категории цен. Это указывает на то, что в выборке присутствует сбалансированное представление автомобилей разных ценовых категорий, что важно для задачи классификации и может способствовать более эффективному обучению модели.